# Generated by Django 3.0 on 2023-12-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_users_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
