# Generated by Django 3.0 on 2023-12-25 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorname', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('bio', models.TextField()),
            ],
            options={
                'db_table': 'Director',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('length', models.IntegerField()),
                ('web', models.URLField(max_length=100)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Director')),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
    ]
