# Generated by Django 3.0 on 2023-12-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_director_movie'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
