# Generated by Django 3.0 on 2023-12-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20231225_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
