# Generated by Django 3.0 on 2023-12-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_movie_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
