# Generated by Django 3.0 on 2023-12-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_director_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
