# Generated by Django 3.0 on 2023-12-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_movie_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(max_length=40),
        ),
    ]
