# Generated by Django 3.0 on 2023-12-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_actor_cast'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'movie')},
        ),
    ]
